function dT_ca = F0012_cathodePlate(T_m, T_ca, T_cp, T_amb, par)
% parameters
C  = par.C_ca;
R5 = par.R5;
R6 = par.R6;
R9 = par.R9;

% output
dT_ca = 1./C .*( ...
                    -(1/R5 + 1/R6 + 1/R9).*T_ca + ...
                        1/R5 .* T_m  + ...
                        1/R9 .* T_cp + ...
                        1/R6 .* T_amb ...
                );
end