function dg = grad_g(in1,in2,m,r_w,gam,beta,dx)
%GRAD_G
%    DG = GRAD_G(IN1,IN2,M,R_W,GAM,BETA,DX)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-Jul-2022 18:47:14

z1 = in1(1,:);
z2 = in1(2,:);
z4 = in1(4,:);
z5 = in1(5,:);
t2 = 1.0./dx;
t3 = 1.0./gam;
t4 = 1.0./r_w;
t5 = -z4;
t6 = -z5;
t7 = beta./2.0;
t8 = z1./2.0;
t9 = z4./2.0;
t10 = t5+z1;
t11 = t6+z2;
t12 = -t7;
t13 = t8+t9;
t14 = (t2.*t11)./2.0;
t15 = (m.*t2.*t10)./2.0;
t17 = t2.*t13;
t16 = -t14;
t18 = m.*t17;
dg = reshape([-t3.*t4.*(t15+t18),t16,-1.0./2.0,t7-t17,0.0,t12,-t3.*t4.*(t15-t18),t16,-1.0./2.0,t7+t17,0.0,t12],[2,6]);
